[package]
name = "hypraway"
version = "1.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
dirs = "5.0"
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }